### ISSUE TITLE
item esp

### ISSUE THREAD

**Issue by 1arsi1** [kristofhracza/tim_apple#4]
I understand why the problem is high CPU consumption when item esp, if you look down, you can see a bunch of icons that merge into one....
![image](https://github.com/kristofhracza/tim_apple/assets/61199844/b8d3b96a-34a8-4cf9-a091-be5b9531c12a)

**Comment by 1arsi1** [comment]
When the items are in everyone's hands, everything is normal, but when at least 1 is lying down, an icon appears underneath it

**Comment by 1arsi1** [comment]
![image](https://github.com/kristofhracza/tim_apple/assets/61199844/6214efc8-cda1-4f3f-bc14-ccaf22eb2cf5)
![image](https://github.com/kristofhracza/tim_apple/assets/61199844/c2b3c852-b6fb-4296-9f31-c001bb9f88c5)

**Comment by kristofhracza** [comment]
I understand what you're trying to say. The 1st part can be fixed. 
The issue regarding the items at random places. Hope that was what you meant.
[Here's](https://github.com/kristofhracza/tim_apple/commit/c2a60c5f51562e26b653588c84059b00b40fe7bb) the one line check that did it

The performance issue wasn't fixed with that. I still believe it is the `for` loop, so I'll add multi-threading later.

If you have another idea, just post it here.

**Comment by 1arsi1** [comment]
No ideas yet, but I will try to help you solve this problem!

**Comment by 1arsi1** [comment]
You know, I was thinking that adding a radius to show dropped item esp would be great to have them shown in a radius of meters through the slider

and it's going to add production

**Comment by kristofhracza** [comment]
Please only update this issue if you have an idea to improve performance, as mentioned [here](https://github.com/kristofhracza/tim_apple/issues/4#issuecomment-1872601921).

For anything else, make another issue.
